name: build-and-test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run Benchmarks
      run: cd SimpleECS.Benchmarks && dotnet run
    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        tool: benchmarkdotnet
        output-file-path: SimpleECS.Benchmarks/results/SimpleECS.Benchmarks-report-full-compressed.json
